In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [14]:
may=pd.read_excel("may.xls")
june=pd.read_excel("june.xls")
july=pd.read_excel("july.xls")

In [15]:
may

                     Name To Display      Qty      Amount         Rate
0                  5 STAR 10 rupees        12      102.60       8.5500
1                  5 STAR CHOCOLATE       153      648.54       4.2388
2          5IN1 ULLAS AGARBATTI 45GM        4       92.00      23.0000
3                AASHIRWAD ATTA-5KG         1      238.10     238.1000
4     ACT II POPCARN SALTED - 120 GM        3       93.72      31.2400
...                              ...      ...         ...          ...
2204            Z TALC FOR MEN-50GM         6      366.12      61.0200
2205            ZANDU BALM ULTRA 8ML        7      300.02      42.8600
2206               ZENDU BALM-9.6ML        11      422.40      38.4000
2207           ZIGGY DONUT CAKE 47GM       22      354.20      16.1000
2208                     Grand Total  1634644  1543183.12  170418.2156

[2209 rows x 4 columns]

In [4]:
june

                  Name To Display      Qty      Amount         Rate
0           333 PURE CAMPHOR 20GM        1       34.00      34.0000
1               5 STAR 10 rupees        25      211.90       8.4760
2               5 STAR CHOCOLATE        94      398.38       4.2381
3       5IN1 ULLAS AGARBATTI 45GM        4       92.00      23.0000
4             AASHIRWAD ATTA-5KG         4      952.40     238.1000
...                           ...      ...         ...          ...
2189         ZANDU BALM ULTRA 8ML        1       42.86      42.8600
2190  ZENDU BALM ULTRA POWER-8ML        15      642.90      42.8600
2191            ZENDU BALM-9.6ML        16      614.40      38.4000
2192        ZIGGY DONUT CAKE 47GM       11      177.10      16.1000
2193                  Grand Total  2340374  1955745.20  167660.1964

[2194 rows x 4 columns]

In [5]:
july

                         Name To Display      Qty      Amount         Rate
0                    172 PAGES NOTEBOOK         1       49.10      49.1000
1                      5 STAR 10 rupees        77      682.84       8.8681
2                      5 STAR CHOCOLATE         5       21.20       4.2400
3                    AASHIRWAD ATTA-5KG         2      476.20     238.1000
4     ACT II POPCORN CLASSIC SALTED 10RS       27      236.14       8.7459
...                                  ...      ...         ...          ...
2021                        Z TALC 100GM        1      140.00     140.0000
2022         ZENDU BALM ULTRA POWER-8ML         3      128.58      42.8600
2023                   ZENDU BALM-9.6ML        12      460.80      38.4000
2024               ZIGGY DONUT CAKE 47GM       13      209.30      16.1000
2025                         Grand Total  1680410  1788302.62  154521.5923

[2026 rows x 4 columns]

In [93]:
conn = sqlite3.connect(':memory:')

In [55]:
may.to_sql('sales_may', conn, index=False, if_exists='replace')
june.to_sql('sales_june', conn, index=False, if_exists='replace')
july.to_sql('sales_july', conn, index=False, if_exists='replace')

2026

In [56]:
query_group_may = """
CREATE TABLE sales_may_summary AS
SELECT [Name To Display], SUM(Qty) as Total_Qty, round(Rate,2),round(sum(Qty)*Rate,2) as Amount
FROM sales_may
GROUP BY [Name To Display];
"""

In [57]:
query_group_june = """
CREATE TABLE sales_june_summary AS
SELECT [Name To Display], SUM(Qty) as Total_Qty,round(Rate,2), round(sum(Qty)*Rate,2) as Amount
FROM sales_june
GROUP BY [Name To Display];
"""

In [58]:
query_group_july = """
CREATE TABLE sales_july_summary AS
SELECT [Name To Display], SUM(Qty) as Total_Qty,round(Rate,2), round(sum(Qty)*Rate,2) as Amount
FROM sales_july
GROUP BY [Name To Display];
"""

In [59]:
cursor = conn.cursor()

In [60]:
cursor.execute("DROP TABLE IF EXISTS sales_may_summary;")
cursor.execute("DROP TABLE IF EXISTS sales_june_summary;")
cursor.execute("DROP TABLE IF EXISTS sales_july_summary;")

In [61]:
cursor.execute(query_group_may)
cursor.execute(query_group_june)
cursor.execute(query_group_july)

In [62]:
conn.commit()

In [63]:
df_may_summary = pd.read_sql_query("SELECT * FROM sales_may_summary", conn)
df_june_summary = pd.read_sql_query("SELECT * FROM sales_june_summary", conn)
df_july_summary = pd.read_sql_query("SELECT * FROM sales_july_summary", conn)

In [64]:
conn.close()

In [65]:
df_may_summary

                     Name To Display  Total_Qty  round(Rate,2)  Amount
0                  5 STAR 10 rupees          12           8.55  102.60
1                  5 STAR CHOCOLATE         153           4.24  648.54
2          5IN1 ULLAS AGARBATTI 45GM          4          23.00   92.00
3                AASHIRWAD ATTA-5KG           1         238.10  238.10
4     ACT II POPCARN SALTED - 120 GM          3          31.24   93.72
...                              ...        ...            ...     ...
2155                    Z TALC 100GM          6         140.00  840.00
2156            Z TALC FOR MEN-50GM           6          61.02  366.12
2157            ZANDU BALM ULTRA 8ML          7          42.86  300.02
2158               ZENDU BALM-9.6ML          11          38.40  422.40
2159           ZIGGY DONUT CAKE 47GM         22          16.10  354.20

[2160 rows x 4 columns]

In [66]:
df_june_summary

,Name To Display,Total_Qty,"round(Rate,2)",Amount
0,333 PURE CAMPHOR 20GM,1,34.00,34.00
1,5 STAR 10 rupees,25,8.48,211.90
2,5 STAR CHOCOLATE,94,4.24,398.38
3,5IN1 ULLAS AGARBATTI 45GM,4,23.00,92.00
4,AASHIRWAD ATTA-5KG,4,238.10,952.40
...,...,...,...,...
2114,clothes clips plastics 24(169),1,51.78,51.78
2115,comfort DESIRE SMELL,3,50.84,152.52
2116,comfort LILY FRESH,31,3.39,105.06
2117,fair and lovely cream 10rs fair and lovely cre...,7,8.93,62.48
2118,livon small 70rs hair serum,1,62.50,62.50

In [67]:
df_july_summary

,Name To Display,Total_Qty,"round(Rate,2)",Amount
0,172 PAGES NOTEBOOK,1,49.10,49.10
1,5 STAR 10 rupees,77,8.87,682.84
2,5 STAR CHOCOLATE,5,4.24,21.20
3,AASHIRWAD ATTA-5KG,2,238.10,476.20
4,ACT II POPCORN CLASSIC SALTED 10RS,27,8.75,236.14
...,...,...,...,...
1979,ZIGGY DONUT CAKE 47GM,13,16.10,209.30
1980,bourn vita biscuit,9,8.05,72.48
1981,comfort LILY FRESH,88,3.39,298.26
1982,fair and lovely cream 10rs fair and lovely cre...,8,8.92,71.38
1983,livon small 70rs hair serum,2,62.50,125.00

In [84]:
df_may_summary.to_sql("raw_may", conn, index=False, if_exists="replace")
df_june_summary.to_sql("raw_june", conn, index=False, if_exists="replace")
df_july_summary.to_sql("raw_july", conn, index=False, if_exists="replace")

1984

In [85]:

master_summary_query = """
SELECT 
    catalog.[Name To Display],
    
    -- May Features (Pull Qty, Calculate Rate, Pull Amount)
    m.Total_Qty AS May_Qty,
    ROUND(m.Amount / m.Total_Qty, 4) AS May_Rate,
    m.Amount AS May_Amount,
    
    -- June Features
    jn.Total_Qty AS June_Qty,
    ROUND(jn.Amount / jn.Total_Qty, 4) AS June_Rate,
    jn.Amount AS June_Amount,
    
    -- July Features
    jl.Total_Qty AS July_Qty,
    ROUND(jl.Amount / jl.Total_Qty, 4) AS July_Rate,
    jl.Amount AS July_Amount

FROM (
    -- Step 1: Collect ALL unique product names across all 3 summaries
    SELECT [Name To Display] FROM raw_may
    UNION
    SELECT [Name To Display] FROM raw_june
    UNION
    SELECT [Name To Display] FROM raw_july
) AS catalog

-- Step 2: Left join the monthly summary tables you uploaded
LEFT JOIN raw_may m ON catalog.[Name To Display] = m.[Name To Display]
LEFT JOIN raw_june jn ON catalog.[Name To Display] = jn.[Name To Display]
LEFT JOIN raw_july jl ON catalog.[Name To Display] = jl.[Name To Display];
"""

In [86]:

df_final_matrix = pd.read_sql_query(master_summary_query, conn)


df_final_matrix = df_final_matrix.fillna(0)


df_final_matrix.to_sql("consolidated_market_matrix", conn, index=False, if_exists="replace")


conn.close()

🎉 Part 2 Complete: Master Consolidated Matrix Compiled!
                   Name To Display  May_Qty  May_Rate  May_Amount  June_Qty  June_Rate  June_Amount  July_Qty  July_Rate  July_Amount
                172 PAGES NOTEBOOK      0.0    0.0000        0.00       0.0     0.0000         0.00       1.0    49.1000        49.10
             333 PURE CAMPHOR 20GM      0.0    0.0000        0.00       1.0    34.0000        34.00       0.0     0.0000         0.00
                  5 STAR 10 rupees     12.0    8.5500      102.60      25.0     8.4760       211.90      77.0     8.8681       682.84
                  5 STAR CHOCOLATE    153.0    4.2388      648.54      94.0     4.2381       398.38       5.0     4.2400        21.20
         5IN1 ULLAS AGARBATTI 45GM      4.0   23.0000       92.00       4.0    23.0000        92.00       0.0     0.0000         0.00
                AASHIRWAD ATTA-5KG      1.0  238.1000      238.10       4.0   238.1000       952.40       2.0   238.1000       476.20
    ACT II POPCARN SALTED - 120 GM      3.0   31.2400       93.72       0.0     0.0000         0.00       0.0     0.0000         0.00
ACT II POPCORN CLASSIC SALTED 10RS     30.0    8.7460      262.38      25.0     8.7480       218.70      27.0     8.7459       236.14
ACT II POPCORN GOLDEN SIZZLE-120GM      2.0   30.3600       60.72       0.0     0.0000         0.00       0.0     0.0000         0.00
      ACTII POPCORN BUTTER-RS.12/-     41.0    8.4805      347.70      78.0     8.4805       661.48      19.0     8.4811       161.14

#WE HAVE SUCCESSFULLY JOIN ALL THE THREE TABLES USING JOIN ,BY USING UNION WE GET EVERY DISTINCT PRODUCT PRESENT IN ALL THE TABLES

In [79]:
df_final_matrix

,Name To Display,May_Qty,May_Rate,May_Amount,June_Qty,June_Rate,June_Amount,July_Qty,July_Rate,July_Amount
0,172 PAGES NOTEBOOK,0.0,0.0000,0.00,0.0,0.0000,0.00,1.0,49.1000,49.10
1,333 PURE CAMPHOR 20GM,0.0,0.0000,0.00,1.0,34.0000,34.00,0.0,0.0000,0.00
2,5 STAR 10 rupees,12.0,8.5500,102.60,25.0,8.4760,211.90,77.0,8.8681,682.84
3,5 STAR CHOCOLATE,153.0,4.2388,648.54,94.0,4.2381,398.38,5.0,4.2400,21.20
4,5IN1 ULLAS AGARBATTI 45GM,4.0,23.0000,92.00,4.0,23.0000,92.00,0.0,0.0000,0.00
...,...,...,...,...,...,...,...,...,...,...
2983,clothes clips plastics 24(169),0.0,0.0000,0.00,1.0,51.7800,51.78,0.0,0.0000,0.00
2984,comfort DESIRE SMELL,0.0,0.0000,0.00,3.0,50.8400,152.52,0.0,0.0000,0.00
2985,comfort LILY FRESH,0.0,0.0000,0.00,31.0,3.3890,105.06,88.0,3.3893,298.26
2986,fair and lovely cream 10rs fair and lovely cre...,0.0,0.0000,0.00,7.0,8.9257,62.48,8.0,8.9225,71.38
2987,livon small 70rs hair serum,0.0,0.0000,0.00,1.0,62.5000,62.50,2.0,62.5000,125.00

HERE BY WE AGREEGATED ALL THE DATA IN ONE SINGLE TABLE

In [ ]:
NOW WE WILL FIND THE AVG RATE OF ALL THREE COLUMNS

In [87]:
import numpy as np

# 1. Isolate the three rate columns and temporarily replace 0 with NaN (Null)
# This prevents 0.0000 from dragging down the average of active months
temp_rates = df_final_matrix[["May_Rate", "June_Rate", "July_Rate"]].replace(0, np.nan)

# 2. Calculate the average across the row (axis=1) ignoring the Null values
# Then fill any completely blank rows back to 0 and round to 4 decimal places
df_final_matrix["Avg_Rate"] = temp_rates.mean(axis=1).fillna(0).round(4)

# Preview the matrix to verify the calculation is exactly as expected
print("🎉 Part 1 Complete: 'Avg_Rate' calculated successfully!")
print(df_final_matrix[["Name To Display", "May_Rate", "June_Rate", "July_Rate", "Avg_Rate"]].head(4))

🎉 Part 1 Complete: 'Avg_Rate' calculated successfully!
         Name To Display  May_Rate  June_Rate  July_Rate  Avg_Rate
0     172 PAGES NOTEBOOK    0.0000     0.0000    49.1000   49.1000
1  333 PURE CAMPHOR 20GM    0.0000    34.0000     0.0000   34.0000
2       5 STAR 10 rupees    8.5500     8.4760     8.8681    8.6314
3       5 STAR CHOCOLATE    4.2388     4.2381     4.2400    4.2390

In [88]:
# 1. Drop the individual monthly rate columns as requested
df_final_matrix.drop(columns=["May_Rate", "June_Rate", "July_Rate"], inplace=True)

# 2. Reorder columns to make the dataset clean and logical to read
final_column_order = [
    "Name To Display", 
    "Avg_Rate",
    "May_Qty", "May_Amount", 
    "June_Qty", "June_Amount", 
    "July_Qty", "July_Amount"
]
df_final_matrix = df_final_matrix[final_column_order]

print("🎉 Success: Individual monthly rate columns removed!")
print("👀 Final Clean Matrix Layout:")
print(df_final_matrix.head(5).to_string(index=False))

🎉 Success: Individual monthly rate columns removed!
👀 Final Clean Matrix Layout:
          Name To Display  Avg_Rate  May_Qty  May_Amount  June_Qty  June_Amount  July_Qty  July_Amount
       172 PAGES NOTEBOOK   49.1000      0.0        0.00       0.0         0.00       1.0        49.10
    333 PURE CAMPHOR 20GM   34.0000      0.0        0.00       1.0        34.00       0.0         0.00
         5 STAR 10 rupees    8.6314     12.0      102.60      25.0       211.90      77.0       682.84
         5 STAR CHOCOLATE    4.2390    153.0      648.54      94.0       398.38       5.0        21.20
5IN1 ULLAS AGARBATTI 45GM   23.0000      4.0       92.00       4.0        92.00       0.0         0.00

In [89]:
df_final_matrix

,Name To Display,Avg_Rate,May_Qty,May_Amount,June_Qty,June_Amount,July_Qty,July_Amount
0,172 PAGES NOTEBOOK,49.1000,0.0,0.00,0.0,0.00,1.0,49.10
1,333 PURE CAMPHOR 20GM,34.0000,0.0,0.00,1.0,34.00,0.0,0.00
2,5 STAR 10 rupees,8.6314,12.0,102.60,25.0,211.90,77.0,682.84
3,5 STAR CHOCOLATE,4.2390,153.0,648.54,94.0,398.38,5.0,21.20
4,5IN1 ULLAS AGARBATTI 45GM,23.0000,4.0,92.00,4.0,92.00,0.0,0.00
...,...,...,...,...,...,...,...,...
2983,clothes clips plastics 24(169),51.7800,0.0,0.00,1.0,51.78,0.0,0.00
2984,comfort DESIRE SMELL,50.8400,0.0,0.00,3.0,152.52,0.0,0.00
2985,comfort LILY FRESH,3.3892,0.0,0.00,31.0,105.06,88.0,298.26
2986,fair and lovely cream 10rs fair and lovely cre...,8.9241,0.0,0.00,7.0,62.48,8.0,71.38
2987,livon small 70rs hair serum,62.5000,0.0,0.00,1.0,62.50,2.0,125.00

In [92]:
inv = pd.read_excel("Current Stock Profits (Summary) .xlsx")
inv

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,PRODUCT,Current Stock(SellLoose),SALE RATE,Closing Stock Value,COST RATE,PURCHASE VALUE,MARGIN%,MARGIN RS
1,DOMS 172-PAGES MATHS NOTEBOOK 176 PAGES,1,60,60,39,39,35,21
2,DEEP BUCKET 60L,1,700,700,630,630,10,70
3,PARLE GOLD 1 KG,9,150,1350,123.39,1110.51,17.74,239.49
4,PARLE GOLD 1 KG,6,150,900,123.39,740.34,17.74,159.66
...,...,...,...,...,...,...,...,...
4065,ODONIL ZIPPER DAFFODIL,15,55,825,33,495,40,330
4066,ODONIL ZIPPER CITRUS 10GM,1,55,55,43.91,43.91,20.163636,11.09
4067,ODONIL ZIPPER CITRUS 10GM,24,55,1320,41.24,989.76,25.018182,330.24
4068,CRYSTAL ZIPPY MOPPY 1N,1,85,85,51.4,51.4,39.529412,33.6
4069,JB ZODIAC AGARBATTI 80GM,1,80,80,52.38,52.38,34.525,27.62

TO MAKE THE 1ST ROW THE COLUMN NAME

In [94]:

# 1. Set the column names to be the values from the first row (index 0)
inv.columns = inv.iloc[0]

# 2. Remove the first row since it is now the header
inv = inv[1:].reset_index(drop=True)

# 3. Rename the index axis to remove the leftover text label '0' if any
inv.columns.name = None

# Preview the newly adjusted directory
print("🎉 Success: First row promoted to column headers!")
print(inv.head(3))

🎉 Success: First row promoted to column headers!
                                   PRODUCT Current Stock(SellLoose) SALE RATE  \
0  DOMS 172-PAGES MATHS NOTEBOOK 176 PAGES                        1        60
1                          DEEP BUCKET 60L                        1       700
2                          PARLE GOLD 1 KG                        9       150

  Closing Stock Value COST RATE PURCHASE VALUE MARGIN% MARGIN RS
0                  60        39             39      35        21
1                 700       630            630      10        70
2                1350    123.39        1110.51   17.74    239.49

In [95]:
inv

,PRODUCT,Current Stock(SellLoose),SALE RATE,Closing Stock Value,COST RATE,PURCHASE VALUE,MARGIN%,MARGIN RS
0,DOMS 172-PAGES MATHS NOTEBOOK 176 PAGES,1,60,60,39,39,35,21
1,DEEP BUCKET 60L,1,700,700,630,630,10,70
2,PARLE GOLD 1 KG,9,150,1350,123.39,1110.51,17.74,239.49
3,PARLE GOLD 1 KG,6,150,900,123.39,740.34,17.74,159.66
4,TIDE LIQ. FL 850ML,4,187,748,144.63,578.52,22.657754,169.48
...,...,...,...,...,...,...,...,...
4064,ODONIL ZIPPER DAFFODIL,15,55,825,33,495,40,330
4065,ODONIL ZIPPER CITRUS 10GM,1,55,55,43.91,43.91,20.163636,11.09
4066,ODONIL ZIPPER CITRUS 10GM,24,55,1320,41.24,989.76,25.018182,330.24
4067,CRYSTAL ZIPPY MOPPY 1N,1,85,85,51.4,51.4,39.529412,33.6
4068,JB ZODIAC AGARBATTI 80GM,1,80,80,52.38,52.38,34.525,27.62

#WE ONLY EXTRACTED TOSE COLUMN WHICH WE NEED

In [103]:
import pandas as pd

# 1. Clean the string names to prevent whitespace mismatching
inv["PRODUCT"] = inv["PRODUCT"].astype(str).str.strip()

# 2. Convert text values into true numbers so Python doesn't throw calculation errors
inv["Current Stock(SellLoose)"] = pd.to_numeric(inv["Current Stock(SellLoose)"], errors='coerce').fillna(0)
inv["PURCHASE VALUE"] = pd.to_numeric(inv["COST RATE"], errors='coerce').fillna(0)
inv["MARGIN%"] = pd.to_numeric(inv["MARGIN%"], errors='coerce').fillna(0)

# 3. Group by the product name and apply different rules for each column
inv_summary = inv.groupby("PRODUCT").agg({
    "Current Stock(SellLoose)": "sum", # Combines physical counts
    "COST RATE": "sum",           # Combines total purchase investment value
    "MARGIN%": "mean"                  # Averages out the percentage profit threshold
}).reset_index()

print("🎉 Part 1 Complete: Warehouse metrics grouped successfully!")
print(inv_summary.head(3))

🎉 Part 1 Complete: Warehouse metrics grouped successfully!
                 PRODUCT  Current Stock(SellLoose)  COST RATE    MARGIN%
0       250 GM MAWA CAKE                         1        100  20.000000
1  333 PURE CAMPHOR 20GM                        29  25.570345  43.177011
2       5 STAR CHOCOLATE                       101       3.85  23.000000

In [104]:
inv_summary

,PRODUCT,Current Stock(SellLoose),COST RATE,MARGIN%
0,250 GM MAWA CAKE,1,100,20.000000
1,333 PURE CAMPHOR 20GM,29,25.570345,43.177011
2,5 STAR CHOCOLATE,101,3.85,23.000000
3,68 PAGES NOOTBOOK,4,18.9,42.727273
4,80X VITAMIN C 80X VITAMIN C,1,100,20.000000
...,...,...,...,...
3592,comfort LILY FRESH,143,6.111955,23.600564
3593,fair and lovely cream 10rs fair and lovely cre...,9,9.09,9.100000
3594,hamam neem soap 150gm(119),6,57.22,21.616438
3595,livon small 70rs hair serum,2,59.99,14.300000
3596,vijay blades 50 n,15,50,23.076923

In [121]:
import pandas as pd

# 1. Ensure product string labels are stripped of hidden trailing spaces to guarantee a perfect match
df_final_matrix["Name To Display"] = df_final_matrix["Name To Display"].astype(str).str.strip()
inv_summary["PRODUCT"] = inv_summary["PRODUCT"].astype(str).str.strip()

# 2. Execute the RIGHT JOIN
# This keeps ALL products from df_final_matrix (sales data matrix)
df_turnaround_master = pd.merge(
    inv_summary, 
    df_final_matrix, 
    left_on="PRODUCT", 
    right_on="Name To Display", 
    how="right"
)

# 3. Clean up the join residue
# Drop the duplicate 'PRODUCT' column from inv_summary, since we have 'Name To Display'
df_turnaround_master.drop(columns=["PRODUCT"], inplace=True, errors="ignore")

# 4. Fill physical stock and financial gaps with 0 where there is currently zero warehouse inventory
fill_inventory_cols = ["Current Stock(SellLoose)", "COST RATE", "MARGIN%"]
df_turnaround_master[fill_inventory_cols] = df_turnaround_master[fill_inventory_cols].fillna(0)

# Optional: Clean up data types (Cast stock counts to clean integers)
df_turnaround_master["Current Stock(SellLoose)"] = df_turnaround_master["Current Stock(SellLoose)"].astype(int)

# Round the financial margins and average rates for clean viewing
df_turnaround_master["MARGIN%"] = df_turnaround_master["MARGIN%"].round(2)
df_turnaround_master["Avg_Rate"] = df_turnaround_master["Avg_Rate"].round(2)

print("🎉 Part 1 Complete: Operational datasets unified via a Right Join!")
print(f"• Total Rows Preserved (All Active Selling Products): {len(df_turnaround_master)}")

🎉 Part 1 Complete: Operational datasets unified via a Right Join!
• Total Rows Preserved (All Active Selling Products): 2988

In [122]:
df_turnaround_master

,Current Stock(SellLoose),COST RATE,MARGIN%,Name To Display,Avg_Rate,May_Qty,May_Amount,June_Qty,June_Amount,July_Qty,July_Amount
0,0,0,0.00,172 PAGES NOTEBOOK,49.10,0.0,0.00,0.0,0.00,1.0,49.10
1,29,25.570345,43.18,333 PURE CAMPHOR 20GM,34.00,0.0,0.00,1.0,34.00,0.0,0.00
2,0,0,0.00,5 STAR 10 rupees,8.63,12.0,102.60,25.0,211.90,77.0,682.84
3,101,3.85,23.00,5 STAR CHOCOLATE,4.24,153.0,648.54,94.0,398.38,5.0,21.20
4,0,0,0.00,5IN1 ULLAS AGARBATTI 45GM,23.00,4.0,92.00,4.0,92.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
2983,11,18,68.97,clothes clips plastics 24(169),51.78,0.0,0.00,1.0,51.78,0.0,0.00
2984,0,0,0.00,comfort DESIRE SMELL,50.84,0.0,0.00,3.0,152.52,0.0,0.00
2985,143,6.111955,23.60,comfort LILY FRESH,3.39,0.0,0.00,31.0,105.06,88.0,298.26
2986,9,9.09,9.10,fair and lovely cream 10rs fair and lovely cre...,8.92,0.0,0.00,7.0,62.48,8.0,71.38
2987,2,59.99,14.30,livon small 70rs hair serum,62.50,0.0,0.00,1.0,62.50,2.0,125.00

In [123]:
# 1. Map out your exact requested column layout sequence
custom_column_sequence = [
    "Name To Display",            # 1. Product Name first
    "Avg_Rate",                   # 2. Combined Average Rate
    "COST RATE",             # 3. Purchase Value
    "MARGIN%",                    # 4. Profit Margin (%)
    "Current Stock(SellLoose)",   # 5. Current Loose Stock
    "May_Qty", "May_Amount",      # 6. Further monthly columns
    "June_Qty", "June_Amount", 
    "July_Qty", "July_Amount"
]

# 2. Re-index your unified dataframe into this precise column order
df_turnaround_master = df_turnaround_master[custom_column_sequence]

# 3. Clean up formatting and data types for presentation
df_turnaround_master["Current Stock(SellLoose)"] = df_turnaround_master["Current Stock(SellLoose)"].astype(int)
df_turnaround_master["May_Qty"] = df_turnaround_master["May_Qty"].fillna(0).astype(int)
df_turnaround_master["June_Qty"] = df_turnaround_master["June_Qty"].fillna(0).astype(int)
df_turnaround_master["July_Qty"] = df_turnaround_master["July_Qty"].fillna(0).astype(int)

df_turnaround_master["MARGIN%"] = df_turnaround_master["MARGIN%"].round(2)
df_turnaround_master["Avg_Rate"] = df_turnaround_master["Avg_Rate"].round(2)

print("🎉 Part 2 Complete: Master Turnaround Directory structured successfully!")
print("👀 Preview of your customized final layout:")
print(df_turnaround_master.head(5).to_string(index=False))

🎉 Part 2 Complete: Master Turnaround Directory structured successfully!
👀 Preview of your customized final layout:
          Name To Display  Avg_Rate  COST RATE  MARGIN%  Current Stock(SellLoose)  May_Qty  May_Amount  June_Qty  June_Amount  July_Qty  July_Amount
       172 PAGES NOTEBOOK     49.10          0     0.00                         0        0        0.00         0         0.00         1        49.10
    333 PURE CAMPHOR 20GM     34.00  25.570345    43.18                        29        0        0.00         1        34.00         0         0.00
         5 STAR 10 rupees      8.63          0     0.00                         0       12      102.60        25       211.90        77       682.84
         5 STAR CHOCOLATE      4.24       3.85    23.00                       101      153      648.54        94       398.38         5        21.20
5IN1 ULLAS AGARBATTI 45GM     23.00          0     0.00                         0        4       92.00         4        92.00         0         0.00

In [124]:
df_turnaround_master

,Name To Display,Avg_Rate,COST RATE,MARGIN%,Current Stock(SellLoose),May_Qty,May_Amount,June_Qty,June_Amount,July_Qty,July_Amount
0,172 PAGES NOTEBOOK,49.10,0,0.00,0,0,0.00,0,0.00,1,49.10
1,333 PURE CAMPHOR 20GM,34.00,25.570345,43.18,29,0,0.00,1,34.00,0,0.00
2,5 STAR 10 rupees,8.63,0,0.00,0,12,102.60,25,211.90,77,682.84
3,5 STAR CHOCOLATE,4.24,3.85,23.00,101,153,648.54,94,398.38,5,21.20
4,5IN1 ULLAS AGARBATTI 45GM,23.00,0,0.00,0,4,92.00,4,92.00,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
2983,clothes clips plastics 24(169),51.78,18,68.97,11,0,0.00,1,51.78,0,0.00
2984,comfort DESIRE SMELL,50.84,0,0.00,0,0,0.00,3,152.52,0,0.00
2985,comfort LILY FRESH,3.39,6.111955,23.60,143,0,0.00,31,105.06,88,298.26
2986,fair and lovely cream 10rs fair and lovely cre...,8.92,9.09,9.10,9,0,0.00,7,62.48,8,71.38
2987,livon small 70rs hair serum,62.50,59.99,14.30,2,0,0.00,1,62.50,2,125.00

In [125]:
import numpy as np
import pandas as pd

# 1. Clean the 'COST RATE' string parameter into true numeric floats
df_turnaround_master["COST RATE"] = pd.to_numeric(
    df_turnaround_master["COST RATE"], errors="coerce"
).fillna(0.0)

# 2. Round the cost rate parameter to 2 decimal places as requested
df_turnaround_master["COST RATE"] = df_turnaround_master["COST RATE"].round(2)

# 3. Permanently drop the old pre-existing 'MARGIN%' column
if "MARGIN%" in df_turnaround_master.columns:
    df_turnaround_master.drop(columns=["MARGIN%"], inplace=True)

print("🎉 Part 1 Complete: Cost rates cleaned and old margin data purged!")
print(df_turnaround_master[["Name To Display", "Avg_Rate", "COST RATE"]].head(3))

🎉 Part 1 Complete: Cost rates cleaned and old margin data purged!
         Name To Display  Avg_Rate  COST RATE
0     172 PAGES NOTEBOOK     49.10       0.00
1  333 PURE CAMPHOR 20GM     34.00      25.57
2       5 STAR 10 rupees      8.63       0.00

In [126]:
df_turnaround_master

,Name To Display,Avg_Rate,COST RATE,Current Stock(SellLoose),May_Qty,May_Amount,June_Qty,June_Amount,July_Qty,July_Amount
0,172 PAGES NOTEBOOK,49.10,0.00,0,0,0.00,0,0.00,1,49.10
1,333 PURE CAMPHOR 20GM,34.00,25.57,29,0,0.00,1,34.00,0,0.00
2,5 STAR 10 rupees,8.63,0.00,0,12,102.60,25,211.90,77,682.84
3,5 STAR CHOCOLATE,4.24,3.85,101,153,648.54,94,398.38,5,21.20
4,5IN1 ULLAS AGARBATTI 45GM,23.00,0.00,0,4,92.00,4,92.00,0,0.00
...,...,...,...,...,...,...,...,...,...,...
2983,clothes clips plastics 24(169),51.78,18.00,11,0,0.00,1,51.78,0,0.00
2984,comfort DESIRE SMELL,50.84,0.00,0,0,0.00,3,152.52,0,0.00
2985,comfort LILY FRESH,3.39,6.11,143,0,0.00,31,105.06,88,298.26
2986,fair and lovely cream 10rs fair and lovely cre...,8.92,9.09,9,0,0.00,7,62.48,8,71.38
2987,livon small 70rs hair serum,62.50,59.99,2,0,0.00,1,62.50,2,125.00

In [ ]:
#AS THE MARGIN % WAS DIFFERENT WE CALCULATED OUR OWN MARGIN ACCORDING TO SALE AND COST RATE

In [127]:
# 4. Mathematically compute Gross Profit Margin % using: ((Price - Cost) / Price) * 100
# np.where handles items with zero sales or zero rates safely to prevent division-by-zero errors
price = df_turnaround_master["Avg_Rate"]
cost = df_turnaround_master["COST RATE"]

calculated_margin = np.where(price > 0, ((price - cost) / price) * 100, 0.0)

# 5. Assign the new values back to a clean 'margin_%' column rounded to 2 decimal places
df_turnaround_master["margin_%"] = np.round(calculated_margin, 2)

# 6. Re-index and sequence columns logically for clean viewing
final_column_layout = [
    "Name To Display",
    "Avg_Rate",
    "COST RATE",
    "margin_%",
    "Current Stock(SellLoose)",
    "May_Qty",
    "May_Amount",
    "June_Qty",
    "June_Amount",
    "July_Qty",
    "July_Amount",
]
df_turnaround_master = df_turnaround_master[final_column_layout]

print("🎉 Part 2 Complete: Custom margin percentages computed safely!")
print("👀 Final Adjusted Table Preview:")
print(df_turnaround_master.head(5).to_string(index=False))

🎉 Part 2 Complete: Custom margin percentages computed safely!
👀 Final Adjusted Table Preview:
          Name To Display  Avg_Rate  COST RATE  margin_%  Current Stock(SellLoose)  May_Qty  May_Amount  June_Qty  June_Amount  July_Qty  July_Amount
       172 PAGES NOTEBOOK     49.10       0.00    100.00                         0        0        0.00         0         0.00         1        49.10
    333 PURE CAMPHOR 20GM     34.00      25.57     24.79                        29        0        0.00         1        34.00         0         0.00
         5 STAR 10 rupees      8.63       0.00    100.00                         0       12      102.60        25       211.90        77       682.84
         5 STAR CHOCOLATE      4.24       3.85      9.20                       101      153      648.54        94       398.38         5        21.20
5IN1 ULLAS AGARBATTI 45GM     23.00       0.00    100.00                         0        4       92.00         4        92.00         0         0.00

In [128]:
df_turnaround_master

,Name To Display,Avg_Rate,COST RATE,margin_%,Current Stock(SellLoose),May_Qty,May_Amount,June_Qty,June_Amount,July_Qty,July_Amount
0,172 PAGES NOTEBOOK,49.10,0.00,100.00,0,0,0.00,0,0.00,1,49.10
1,333 PURE CAMPHOR 20GM,34.00,25.57,24.79,29,0,0.00,1,34.00,0,0.00
2,5 STAR 10 rupees,8.63,0.00,100.00,0,12,102.60,25,211.90,77,682.84
3,5 STAR CHOCOLATE,4.24,3.85,9.20,101,153,648.54,94,398.38,5,21.20
4,5IN1 ULLAS AGARBATTI 45GM,23.00,0.00,100.00,0,4,92.00,4,92.00,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
2983,clothes clips plastics 24(169),51.78,18.00,65.24,11,0,0.00,1,51.78,0,0.00
2984,comfort DESIRE SMELL,50.84,0.00,100.00,0,0,0.00,3,152.52,0,0.00
2985,comfort LILY FRESH,3.39,6.11,-80.24,143,0,0.00,31,105.06,88,298.26
2986,fair and lovely cream 10rs fair and lovely cre...,8.92,9.09,-1.91,9,0,0.00,7,62.48,8,71.38
2987,livon small 70rs hair serum,62.50,59.99,4.02,2,0,0.00,1,62.50,2,125.00

In [130]:
# 1. Establish the filter condition: COST RATE must equal 0 AND margin_% must equal 100
anomalous_condition = (df_turnaround_master["COST RATE"] == 0) & (df_turnaround_master["margin_%"] == 100)

# 2. Extract these specific records into an independent DataFrame object
df_unrealistic_margins = df_turnaround_master[anomalous_condition].copy()

# 3. Reset index for clean data listing
df_unrealistic_margins.reset_index(drop=True, inplace=True)

print("=========================================================================")
print("🚨 AUDIT REPORT: INCOMPLETE COST LOGGING RATIO DIRECTORY")
print("=========================================================================")
print(f"• Total Data Discrepancy SKU Lines Found: {len(df_unrealistic_margins)}")

=========================================================================
🚨 AUDIT REPORT: INCOMPLETE COST LOGGING RATIO DIRECTORY
=========================================================================
• Total Data Discrepancy SKU Lines Found: 1315

In [119]:
df_turnaround_master

,Name To Display,Avg_Rate,COST RATE,margin_%,Current Stock(SellLoose),May_Qty,May_Amount,June_Qty,June_Amount,July_Qty,July_Amount
0,333 PURE CAMPHOR 20GM,34.00,25.57,24.79,29,0,0.00,1,34.00,0,0.00
1,5 STAR CHOCOLATE,4.24,3.85,9.20,101,153,648.54,94,398.38,5,21.20
2,ACT II POPCORN GOLDEN SIZZLE-120GM,30.36,29.67,2.27,2,2,60.72,0,0.00,0,0.00
3,ACTII POPCORN BUTTER-RS.12/-,8.48,7.80,8.02,40,41,347.70,78,661.48,19,161.14
4,ACTII POPCORN GOLDEN SIZZLE 38GM,8.75,7.80,10.86,56,41,358.68,34,297.42,36,314.92
...,...,...,...,...,...,...,...,...,...,...,...
1668,clothes clips clothes clips plastics 12N(168),89.28,42.00,52.96,4,0,0.00,2,178.56,0,0.00
1669,clothes clips plastics 24(169),51.78,18.00,65.24,11,0,0.00,1,51.78,0,0.00
1670,comfort LILY FRESH,3.39,6.11,-80.24,143,0,0.00,31,105.06,88,298.26
1671,fair and lovely cream 10rs fair and lovely cre...,8.92,9.09,-1.91,9,0,0.00,7,62.48,8,71.38
1672,livon small 70rs hair serum,62.50,59.99,4.02,2,0,0.00,1,62.50,2,125.00

In [131]:
df_unrealistic_margins  #THIS ARE THE PRODUCTS WHO ARE MISTAKENLY ENTERED ,EITHER THIS THIS FAILURE OF PURCHASING ASSISTANT WHO DIDNT ENTERD THE COST VALUE FOR THIS

,Name To Display,Avg_Rate,COST RATE,margin_%,Current Stock(SellLoose),May_Qty,May_Amount,June_Qty,June_Amount,July_Qty,July_Amount
0,172 PAGES NOTEBOOK,49.10,0.0,100.0,0,0,0.00,0,0.00,1,49.10
1,5 STAR 10 rupees,8.63,0.0,100.0,0,12,102.60,25,211.90,77,682.84
2,5IN1 ULLAS AGARBATTI 45GM,23.00,0.0,100.0,0,4,92.00,4,92.00,0,0.00
3,AASHIRWAD ATTA-5KG,238.10,0.0,100.0,0,1,238.10,4,952.40,2,476.20
4,ACT II POPCARN SALTED - 120 GM,31.24,0.0,100.0,0,3,93.72,0,0.00,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
1310,YIPEE NOODLES 240GM,45.54,0.0,100.0,0,1,45.54,0,0.00,0,0.00
1311,YUMMIEZ PERI PERI,107.14,0.0,100.0,0,0,0.00,0,0.00,1,107.14
1312,Z TALC FOR MEN-50GM,61.02,0.0,100.0,0,6,366.12,5,305.10,0,0.00
1313,ZENDU BALM-9.6ML,38.40,0.0,100.0,0,11,422.40,16,614.40,12,460.80
1314,comfort DESIRE SMELL,50.84,0.0,100.0,0,0,0.00,3,152.52,0,0.00

In [132]:
df_turnaround_master.to_excel("final_dataset.xlsx")#THIS IS FINAL TABLE
df_unrealistic_margins.to_excel("unrealistic_margin.xlsx")#WE SPOTTED THAT THERE ARE MANY 100% PRODUCTS THAT IS TYPOS OR SOME OF THEM COULD BE FREE PRODUCTS